import PostCard from "@/components/card/PostCard";
import Category from "@/components/pageSections/homepage/Categories";
import Months from "@/components/pageSections/homepage/Months";
import getBlogs from "@/contentful/blogs";
import getCategories from "@/contentful/slug";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-10">
        <div className="col-span-2">
          <Category />
        </div>
        <div className="col-span-8 border-l-[1px] border-solid border-white/10">
          <div className="bg-black z-20 sticky top-0 py-2 border-b-[1px] border-solid border-white/10">
            <Months />
          </div>
          <div className="p-5">
            <RecentPosts />
          </div>
        </div>
      </div>
    </>
  );
}

const RecentPosts = () => {
  return (
    <>
      <div className="grid grid-flow-row grid-cols-2 gap-4">
        <PostCard />
        <PostCard />
        <PostCard />
        <PostCard />
        <PostCard />
        <PostCard />
        <PostCard />
        <PostCard />
        <PostCard />
        <PostCard />
      </div>
    </>
  );
};
