import getBlogs from "@/contentful/blogs";
import getCategories from "@/contentful/categories";
import { CategoryType } from "@/types/category";
import { BlogsType } from "@/types/blogs";
import { GetServerSideProps } from "next";
import Head from "next/head";
import BlogPosts from "@/components/BlogPosts";
import CategorySidebarLayout from "@/components/layout/CategorySidebarLayout";

type PropsType = {
  recentBlogs: BlogsType;
  categories: CategoryType;
};

export default function Home({ recentBlogs, categories }: PropsType) {
  // console.log(JSON.stringify(categories));
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CategorySidebarLayout categories={categories}>
        <BlogPosts blogPosts={recentBlogs} />
      </CategorySidebarLayout>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const recentBlogs = await getBlogs();
  const categories = await getCategories();
  return {
    props: {
      recentBlogs,
      categories,
    },
  };
};
